//! Corpus regression runner for OmniScope resource analysis.
//!
//! Runs the full pipeline on each `.ll` file in `tests/integration/`,
//! collects statistics (candidate_count, reportable_count,
//! explained_safe_count, suppressed_count), and writes them to JSON.
//!
//! # Usage
//!
//! ```bash
//! cargo test --test corpus_regression -- --nocapture
//! ```
//!
//! The JSON output is printed to stdout for capture by CI scripts.

use omniscope_ir::IRModule;
use omniscope_pipeline::Pipeline;
use std::path::PathBuf;
use tracing::info;

/// Statistics for a single corpus file.
#[derive(Debug, Clone)]
pub struct CorpusStats {
    /// File name (relative path).
    pub file: String,
    /// Number of issue candidates generated by IssueCandidateBuilder.
    pub candidate_count: usize,
    /// Number of reportable issues (passed verifier + SRT gate).
    pub reportable_count: usize,
    /// Number of issues suppressed by the SRT gate.
    pub suppressed_count: usize,
    /// Total nodes analyzed across all passes.
    pub total_nodes: usize,
    /// Number of passes executed.
    pub pass_count: usize,
}

impl CorpusStats {
    /// Converts to a JSON string.
    pub fn to_json(&self) -> String {
        format!(
            r#"{{"file":"{}","candidate_count":{},"reportable_count":{},"suppressed_count":{},"total_nodes":{},"pass_count":{}}}"#,
            self.file,
            self.candidate_count,
            self.reportable_count,
            self.suppressed_count,
            self.total_nodes,
            self.pass_count
        )
    }
}

/// Objective: Verify corpus regression produces valid statistics for
/// each integration test file.
/// Invariants: Each file must produce a valid CorpusStats entry,
/// even if the pipeline finds zero issues.
#[test]
fn test_corpus_regression() {
    let corpus_dir = PathBuf::from("tests/integration");
    let mut results: Vec<CorpusStats> = Vec::new();

    // Collect all .ll files in the corpus directory
    let ll_files: Vec<PathBuf> = std::fs::read_dir(&corpus_dir)
        .unwrap_or_else(|e| {
            info!("Cannot read corpus dir {:?}: {}", corpus_dir, e);
            panic!("Corpus directory must exist for regression tests");
        })
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.path().extension().is_some_and(|ext| ext == "ll"))
        .map(|entry| entry.path())
        .collect();

    info!("Corpus regression: {} .ll files", ll_files.len());

    for ll_file in &ll_files {
        let file_name = ll_file.file_name().unwrap().to_string_lossy().to_string();

        // Load the IR module
        let module = match IRModule::load_from_file(ll_file) {
            Ok(m) => m,
            Err(_) => {
                info!("  [SKIP] {} — could not load IR", file_name);
                results.push(CorpusStats {
                    file: file_name,
                    candidate_count: 0,
                    reportable_count: 0,
                    suppressed_count: 0,
                    total_nodes: 0,
                    pass_count: 0,
                });
                continue;
            }
        };

        // Build and run pipeline
        let mut pipeline = Pipeline::new();
        pipeline.register_default_passes();
        pipeline.set_ir_module(module);

        let pipeline_result = pipeline.run().unwrap_or_else(|e| {
            info!("  [ERROR] {} — pipeline failed: {}", file_name, e);
            panic!("Pipeline must not fail on corpus files");
        });

        // Collect stats from pipeline result
        let reportable_count = pipeline_result.issues.len();
        let total_nodes = pipeline_result.total_nodes;
        let pass_count = pipeline_result.pass_count();

        // Try to get candidate and suppressed counts from pass results
        let candidate_count: usize = pipeline_result
            .pass_results
            .iter()
            .find(|r| r.name == "IssueCandidateBuilder")
            .map(|r| r.nodes_analyzed)
            .unwrap_or(0);

        let suppressed_count: usize = pipeline_result
            .pass_results
            .iter()
            .find(|r| r.name == "IssueVerifier")
            .and_then(|r| r.stats.get("gate_suppressed"))
            .copied()
            .unwrap_or(0);

        info!(
            "  {} candidates={}, reportable={}, suppressed={}, nodes={}",
            file_name, candidate_count, reportable_count, suppressed_count, total_nodes
        );

        results.push(CorpusStats {
            file: file_name,
            candidate_count,
            reportable_count,
            suppressed_count,
            total_nodes,
            pass_count,
        });
    }

    // Build aggregate result
    let total_candidates: usize = results.iter().map(|r| r.candidate_count).sum();
    let total_reportable: usize = results.iter().map(|r| r.reportable_count).sum();
    let total_suppressed: usize = results.iter().map(|r| r.suppressed_count).sum();

    // Format as JSON for CI capture
    let file_jsons: Vec<String> = results.iter().map(|r| r.to_json()).collect();
    info!("\n=== Corpus Regression JSON ===");
    info!(
        r#"{{\"total_candidates\":{},\"total_reportable\":{},\"total_suppressed\":{},\"files":[{}]}}"#,
        total_candidates,
        total_reportable,
        total_suppressed,
        file_jsons.join(",")
    );

    // Sanity check: must have at least one file
    assert!(
        !results.is_empty(),
        "Corpus regression must process at least one .ll file"
    );
}
